title: Dark Hacking Site
author:
  name: root
  email: root@sudo.net
  twitter: daulpavid
  mastodon_instance: infosec.exchange
  mastodon_handle: daulpavid
  github: daulpavid
  linkedin: daulpavid
description:
  Bullshit goes here.
tagline:
  Hack the planet!

darkhack:
  date_format: "%x"
  font_awesome: "357d91f838"

theme: darkhack

collections:
  disclosures:
    output: true
